---
title: "Resume"
---

**Mehana Leafchild**

Honolulu, HI \| 808-725-0243 \| [Mehanaleafchild\@gmail.com](mailto:Mehanaleafchild@gmail.com) \| [www.linkedin.com/in/mehanaleafchild](http://www.linkedin.com/in/mehanaleafchild)

\

+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **PROFESSIONAL SUMMARY**                                                                                                                                                                                                                                                                                                                                                                               |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Highly motivated and results-oriented sophomore-year nursing student with a passion for healthcare. Seeking a challenging internship at Kaiser Permanente to gain valuable experience in a dynamic healthcare setting while contributing to departmental success. Possess strong communication, research, and analytical skills, honed through academic pursuits and diverse work experiences.         |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                                                                                                                                                                                                                                                                                        |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **SKILLS**                                                                                                                                                                                                                                                                                                                                                                                             |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Leader, Diligent, Determined, Timely, Communication, Organization, Hard Working, Laboratory experience, Intense Field Work Experience, Research Experience, Community engagement, Problem-Solving, Personable, Time Management, Social Media, R                                                                                                                                                        |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                                                                                                                                                                                                                                                                                        |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **EDUCATION**                                                                                                                                                                                                                                                                                                                                                                                          |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Chaminade University of Honolulu**, Honolulu, HI                                                                                                                                                                                                                                                                                                                                                     |
|                                                                                                                                                                                                                                                                                                                                                                                                        |
| Bachelor of Science, Nursing, Expected Graduation Date: May 2026                                                                                                                                                                                                                                                                                                                                       |
|                                                                                                                                                                                                                                                                                                                                                                                                        |
| -   Current GPA: 3.8                                                                                                                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                                                                                                                                                                                        |
| **Punahou School,** Honolulu, HI                                                                                                                                                                                                                                                                                                                                                                       |
|                                                                                                                                                                                                                                                                                                                                                                                                        |
| -   Presidents Award                                                                                                                                                                                                                                                                                                                                                                                   |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                                                                                                                                                                                                                                                                                        |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **EXPERIENCE**                                                                                                                                                                                                                                                                                                                                                                                         |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **NOAA Science communication internship**                                                                                                                                                                                                                                                                                                                                                              |
|                                                                                                                                                                                                                                                                                                                                                                                                        |
| Intern, May 2024 - August 2024                                                                                                                                                                                                                                                                                                                                                                         |
|                                                                                                                                                                                                                                                                                                                                                                                                        |
| -   Engaged with working Scientists to create meaningful outreach media and educational tools.                                                                                                                                                                                                                                                                                                         |
|                                                                                                                                                                                                                                                                                                                                                                                                        |
| -   Facilitated laboratory tours and school field trips to the laboratory.                                                                                                                                                                                                                                                                                                                             |
|                                                                                                                                                                                                                                                                                                                                                                                                        |
| -   Conducted work at a remote field station analyzing salmon hatchery dynamics.                                                                                                                                                                                                                                                                                                                       |
|                                                                                                                                                                                                                                                                                                                                                                                                        |
| **REU in Environmental Biology**                                                                                                                                                                                                                                                                                                                                                                       |
|                                                                                                                                                                                                                                                                                                                                                                                                        |
| Intern, May 2022 - August 2022                                                                                                                                                                                                                                                                                                                                                                         |
|                                                                                                                                                                                                                                                                                                                                                                                                        |
| -   Conducted lab and field work through UH Manoa.                                                                                                                                                                                                                                                                                                                                                     |
|                                                                                                                                                                                                                                                                                                                                                                                                        |
| -   Developed a complete research proposal and paper with significant results.                                                                                                                                                                                                                                                                                                                         |
|                                                                                                                                                                                                                                                                                                                                                                                                        |
| -   Engaged in cultural application of scientific research being done.                                                                                                                                                                                                                                                                                                                                 |
|                                                                                                                                                                                                                                                                                                                                                                                                        |
| **Brick Fire Tavern,** Server, September 2023 - Present                                                                                                                                                                                                                                                                                                                                                |
|                                                                                                                                                                                                                                                                                                                                                                                                        |
| -   Provided meaningful guest engagement and relationships.                                                                                                                                                                                                                                                                                                                                            |
|                                                                                                                                                                                                                                                                                                                                                                                                        |
| -   Helped create an efficient positive work environment.                                                                                                                                                                                                                                                                                                                                              |
|                                                                                                                                                                                                                                                                                                                                                                                                        |
| **3Rwater,** Field Technician, November 2023 - August 2024                                                                                                                                                                                                                                                                                                                                             |
|                                                                                                                                                                                                                                                                                                                                                                                                        |
| -   Led community members through sustainable rainwater assessments.                                                                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                                                                                                                                                                                        |
| -   Conducted research and development for 3Rwaters’s mobile app.                                                                                                                                                                                                                                                                                                                                      |
|                                                                                                                                                                                                                                                                                                                                                                                                        |
| **Roberta Oaks,** Sales Associate, October 2023 - January 2024                                                                                                                                                                                                                                                                                                                                         |
|                                                                                                                                                                                                                                                                                                                                                                                                        |
| -   Proficiently operated cash register systems, ensuring accurate and efficient transactions while maintaining a positive and professional demeanor.                                                                                                                                                                                                                                                  |
|                                                                                                                                                                                                                                                                                                                                                                                                        |
| -   Maintained an organized store front.                                                                                                                                                                                                                                                                                                                                                               |
|                                                                                                                                                                                                                                                                                                                                                                                                        |
| -   Had significant product knowledge.                                                                                                                                                                                                                                                                                                                                                                 |
|                                                                                                                                                                                                                                                                                                                                                                                                        |
| **Volcom Retail,** Sales Associate, August 2021 - July 2023                                                                                                                                                                                                                                                                                                                                            |
|                                                                                                                                                                                                                                                                                                                                                                                                        |
| -   Kindly welcomed customers and helped with any question they may have.                                                                                                                                                                                                                                                                                                                              |
|                                                                                                                                                                                                                                                                                                                                                                                                        |
| -   Maintained a productive work environment by always conducting tasks.                                                                                                                                                                                                                                                                                                                               |
|                                                                                                                                                                                                                                                                                                                                                                                                        |
| **IT Client Services,** Customer Service, January 2022 - August 2022                                                                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                                                                                                                                                                                        |
| -   Maintained an organized tasks service for our technicians.                                                                                                                                                                                                                                                                                                                                         |
|                                                                                                                                                                                                                                                                                                                                                                                                        |
| -   Constructed emails replying to service tickets.                                                                                                                                                                                                                                                                                                                                                    |
|                                                                                                                                                                                                                                                                                                                                                                                                        |
| -   Communicated clearly and kindly with recipients over the phone and in person.                                                                                                                                                                                                                                                                                                                      |
|                                                                                                                                                                                                                                                                                                                                                                                                        |
| **Taste of The Tropics,** Sales Associate, November 2023 - Present                                                                                                                                                                                                                                                                                                                                     |
|                                                                                                                                                                                                                                                                                                                                                                                                        |
| -   Provided exemplary customer service.                                                                                                                                                                                                                                                                                                                                                               |
|                                                                                                                                                                                                                                                                                                                                                                                                        |
| -   Assisted in product selection.                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                                                                                                                                                                                                                                                                                                                                                        |
| -   Integral in meeting sales goals.                                                                                                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                                                                                                                                                                                        |
| **Moanalua Gardens,** Internship, May 2020 - August 2020                                                                                                                                                                                                                                                                                                                                               |
|                                                                                                                                                                                                                                                                                                                                                                                                        |
| -   Strengthened my leadership and communication skills by guiding students through complex sustainability topics and engaging them in hands-on activities.                                                                                                                                                                                                                                            |
|                                                                                                                                                                                                                                                                                                                                                                                                        |
| -   Enhanced my ability to simplify difficult concepts and fostered teamwork while leading group discussions and examples.                                                                                                                                                                                                                                                                             |
|                                                                                                                                                                                                                                                                                                                                                                                                        |
| **Kupu,** environmental intern, May 2019 - August 2019                                                                                                                                                                                                                                                                                                                                                 |
|                                                                                                                                                                                                                                                                                                                                                                                                        |
| -   Working to restore native forest and natural areas. This ranged from removing invasive plants, setting rat traps, tagging native birds, and planting native plants within nature reserves.                                                                                                                                                                                                         |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                                                                                                                                                                                                                                                                                        |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **PROJECTS**                                                                                                                                                                                                                                                                                                                                                                                           |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Limu and Water Quality Analysis**, Chaminade University, Honolulu, HI January 2021 - Present                                                                                                                                                                                                                                                                                                         |
|                                                                                                                                                                                                                                                                                                                                                                                                        |
| -   Collaborating with a team of students at Chaminade University to study the development and distribution of limu (Hawaiian seaweed) at Kaalawai (Cromwell's Beach). Our research focuses on analyzing water quality and limu growth patterns, with an emphasis on understanding the impact of nutrient-rich runoff following heavy rainfall and distinguishing between native and invasive species. |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

**Mosquito Research,** UH Manoa, Honolulu, HI, May 2022 - August 2022

-    **In the summer of 2022 I was selected to conduct research of my choice at the University of Hawaii at Manoa. I worked on my research project while also learning the cultural and spiritual prevalence native Hawaiians have with science. My research project looked at invasive Culex quinquefasciatus and how their microbiome relates to cold tolerance. This research was key to understanding effective eradication efforts of mosquitoes. Mosquitoes are invasive in Hawaii and spread avian malaria to native birds. I was able to determine that microbiome diversity leads to more cold tolerant mosquitoes and completed a research paper and I'm hoping to get published.**

**Scientific Storytelling,** Auke Bay Laboratories, Ted Stevens Marine Research Institute, Juneau, AK May 2024 - August 2024

-   Conducted science communication work at NOAA's Auke Bay Laboratories, creating infographics, videos, and hands-on tools to engage the community and educate young scientists. Led outreach efforts for key research projects, organized lab tours, and participated in community events like STEAM night. Collaborated with scientists to translate complex research into accessible formats, supporting NOAA's mission to inform and serve the public.

**Inana Innovators,** Chaminade University, Honolulu, HI January 2024 - May 2024

-   Collaborating with business owner [Lauren Roth Venu](mailto:lauren@3r-water.com) engaging in sustainable solutions to water issues stemming from Hawaii's infrastructure. II was responsible for conducting site visits with community members communicating products and services while also incorporating meaningful insights as to why climate resilience is important. 

**All-spice Research Experience,** Chaminade University, Honolulu, HI October 2024 - Present

-   Designed and implemented a hypothesis using data collected by the University. Conducted a full analysis within R studio looking at the correlation between rainfall and water quality and seaweed presence at an ecological site.
